'use client';
import './quantum.css';
import './item10.css';
import { useEffect,useRef,useState,type CSSProperties } from 'react';
import {Activity,BarChart3,Bot,BrainCircuit,CheckCircle2,ChevronLeft,CircleAlert,Clipboard,Database,Download,Edit3,Eye,EyeOff,FileArchive,FileCode2,FileImage,FileSearch,FileText,FolderOpen,Gauge,Globe2,History,Image as ImageIcon,LayoutGrid,Link2,LockKeyhole,Menu,MessageSquare,Mic,MonitorUp,MoreHorizontal,Paperclip,Play,Plus,Save,Search,Send,Settings2,ShieldCheck,Square,Trash2,Video,Volume2,WandSparkles,X,Zap} from 'lucide-react';
import type {AmarAgentBridge,AmarAgentResponse,AmarAgentStatus,AmarProgressStage,AmarSource} from './amarAgentBridge';
type ViewId='home'|'assistant'|'research'|'workspace'|'files'|'memory'|'analytics'|'settings'; type PanelId='core'|'progress'|'sources'|'composer'|'activity'|'editor'; type SearchMode='restricted'|'open'; type Note={id:string;title:string;body:string}; type Props={bridge?:AmarAgentBridge}; type Capabilities=NonNullable<AmarAgentBridge['capabilities']>;
const nav:{id:ViewId;label:string;icon:typeof Bot}[]=[['home','المحور',LayoutGrid],['assistant','AI Assistant',Bot],['research','Research',Globe2],['workspace','Workspace',FolderOpen],['files','Files',Paperclip],['memory','Memory',BrainCircuit],['analytics','Analytics',BarChart3],['settings','Settings',Settings2]].map(([id,label,icon])=>({id:id as ViewId,label:label as string,icon:icon as typeof Bot}));
const stages:{id:AmarProgressStage;label:string}[]=[['understanding','فهم الطلب'],['planning','وضع خطة'],['searching','البحث'],['source_analysis','تحليل المصادر'],['evidence_comparison','مقارنة الأدلة'],['conflict_check','فحص التعارض'],['verification','التحقق'],['preparing_result','تجهيز النتيجة']].map(([id,label])=>({id:id as AmarProgressStage,label:label as string}));
const meta:Record<AmarAgentStatus,{label:string;tone:string}>={ready:{label:'جاهز',tone:'ok'},thinking:{label:'فهم الطلب',tone:'ai'},searching:{label:'البحث',tone:'wait'},analyzing:{label:'تحليل المصادر',tone:'ai'},learning:{label:'التحقق',tone:'ai'},complete:{label:'اكتمل',tone:'ok'},error:{label:'خطأ',tone:'danger'},uncertain:{label:'غير مؤكد',tone:'wait'},blocked:{label:'محجوب',tone:'danger'}};
const terminal:AmarAgentStatus[]=['complete','error','uncertain','blocked'];
const blocked=(text:string):AmarAgentResponse=>({id:crypto.randomUUID(),text,status:'blocked',verification:'blocked'});
export default function Item10Workspace({bridge}:Props){
 const [view,setView]=useState<ViewId>('home'),[status,setStatus]=useState<AmarAgentStatus>('ready'),[response,setResponse]=useState<AmarAgentResponse|null>(null),[message,setMessage]=useState(''),[sources,setSources]=useState<AmarSource[]>([]),[searchMode,setSearchMode]=useState<SearchMode>('restricted'),[progress,setProgress]=useState<AmarProgressStage|null>(null),[sharing,setSharing]=useState(false),[mobile,setMobile]=useState(false),[theme,setTheme]=useState<'aurora'|'obsidian'>('aurora'),[evidence,setEvidence]=useState(false),[panels,setPanels]=useState<Record<PanelId,boolean>>({core:true,progress:true,sources:true,composer:true,activity:true,editor:true}),[color,setColor]=useState('#dff7fb'),[size,setSize]=useState(16),[weight,setWeight]=useState(400),[palette,setPalette]=useState(false),[notes,setNotes]=useState<Note[]>([]),[activeNote,setActiveNote]=useState<string|null>(null),[draft,setDraft]=useState(''),[scale,setScale]=useState(100);
 const fileRef=useRef<HTMLInputElement>(null),imageRef=useRef<HTMLInputElement>(null),videoRef=useRef<HTMLInputElement>(null); const active=nav.find(n=>n.id===view)||nav[0],Icon=active.icon,m=meta[status],running=!terminal.includes(status)&&status!=='ready',cap:Capabilities=bridge?.capabilities||{};
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem('amar-ui-settings')||'null');if(x){x.theme&&setTheme(x.theme);x.color&&setColor(x.color);x.size&&setSize(Math.min(32,Math.max(12,x.size)));x.weight&&setWeight(Math.min(800,Math.max(300,x.weight)));x.scale&&setScale(Math.min(120,Math.max(80,x.scale)));x.notes&&setNotes(x.notes)}}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem('amar-ui-settings',JSON.stringify({theme,color,size,weight,scale,notes}))}catch{}},[theme,color,size,weight,scale,notes]);
 useEffect(()=>bridge?.onStatus?.(setStatus),[bridge]); useEffect(()=>bridge?.onProgress?.(setProgress),[bridge]);
 const toggle=(p:PanelId)=>setPanels(x=>({...x,[p]:!x[p]})); const all=(v:boolean)=>setPanels({core:v,progress:v,sources:v,composer:v,activity:v,editor:v});
 const apply=(r:AmarAgentResponse)=>{setResponse(r);if(r.sources)setSources(r.sources);if(r.progressStage)setProgress(r.progressStage);setStatus(r.status==='complete'&&r.verification==='confirmed'?'complete':r.status==='blocked'?'blocked':r.status==='error'?'error':'uncertain');setEvidence(false)};
 async function submit(){const p=message.trim();if(!p)return;if(!bridge?.send){setStatus('blocked');setResponse(blocked('التنفيذ غير متاح: لا يوجد عقد Item 10 متصل بهذه الواجهة.'));return}setMessage('');setResponse(null);setProgress('understanding');setStatus('thinking');try{apply(await bridge.send({id:crypto.randomUUID(),prompt:p,mode:view,searchMode}))}catch{setStatus('error');setResponse({...blocked('تعذر الحصول على حالة صحيحة من طبقة Item 10.'),status:'error'})}}
 async function research(){const q=message.trim();if(!q)return;if(!bridge?.search){setStatus('blocked');setResponse(blocked('البحث غير متاح بعد في عقد Item 10 المتصل.'));return}setStatus('searching');setProgress('searching');try{const r=await bridge.search(q,searchMode);setSources(r);setProgress(r.length?'verification':'conflict_check');setStatus('uncertain')}catch{setStatus('error');setResponse({...blocked('تعذر الحصول على نتيجة بحث موثقة.'),status:'error'})}}
 async function analyze(f:File){if(!bridge?.analyzeFile){setStatus('blocked');setResponse(blocked('تحليل هذا الملف غير متاح بعد في عقد Item 10 المتصل.'));return}setResponse(null);setProgress('understanding');setStatus('analyzing');try{apply(await bridge.analyzeFile(f))}catch{setStatus('error');setResponse({...blocked('تعذر الحصول على حالة تحقق صحيحة لتحليل الملف.'),status:'error'})}}
 async function share(){if(!sharing){if(!bridge?.startScreenShare||cap.screenShare===false){setStatus('blocked');setResponse(blocked('مشاركة الشاشة غير متاحة بعد في عقد Item 10 المتصل.'));return}try{await bridge.startScreenShare();setSharing(true)}catch{setStatus('blocked');setSharing(false)}}else{bridge?.stopScreenShare?.();setSharing(false)}}
 const copy=async(t:string)=>{try{await navigator.clipboard.writeText(t)}catch{}}; const paste=async()=>{try{const t=await navigator.clipboard.readText();setDraft(v=>v+t)}catch{}};
 const create=()=>{const id=crypto.randomUUID();setNotes(x=>[...x,{id,title:`صفحة ${x.length+1}`,body:''}]);setActiveNote(id);setDraft('')}; const open=(n:Note)=>{setActiveNote(n.id);setDraft(n.body)}; const save=()=>activeNote&&setNotes(x=>x.map(n=>n.id===activeNote?{...n,body:draft}:n)); const del=()=>{if(activeNote)setNotes(x=>x.filter(n=>n.id!==activeNote));setActiveNote(null);setDraft('')};
 const stage=progress?stages.findIndex(s=>s.id===progress):-1, hasEvidence=Boolean((response?.sources?.length||sources.length)&&cap.evidence===true), style:CSSProperties={color,fontSize:size,fontWeight:weight};
 return <main className={`quantum-app theme-${theme}`} dir="rtl" style={{'--card-scale':`${scale/100}`} as CSSProperties}><div className="q-ambient ambient-a"/><div className="q-ambient ambient-b"/><div className="q-grid"/>
 <header className="q-topbar glass"><div className="q-brand"><button className="q-logo" onClick={()=>setView('home')}><span>Q</span><i/></button><div><strong>AMAR AI</strong><small>ITEM 10 UI · AGENT BOUNDARY</small></div></div><div className="q-top-center"><span className={`status-dot ${m.tone}`}/><b>{m.label}</b><em>·</em><span>Presentation / Interaction Layer</span></div><div className="q-top-actions"><button onClick={()=>all(true)}><Eye size={16}/></button><button onClick={()=>all(false)}><EyeOff size={16}/></button><button onClick={()=>setTheme(theme==='aurora'?'obsidian':'aurora')}><WandSparkles size={16}/></button><button onClick={()=>setMobile(!mobile)} className="mobile-only"><Menu size={18}/></button></div></header>
 <div className="q-shell"><aside className={`q-sidebar glass ${mobile?'mobile-open':''}`}><div className="q-sidebar-head"><span>AMAR AI</span><button onClick={()=>setMobile(false)}><X size={15}/></button></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>{setView(n.id);setMobile(false)}}><n.icon size={17}/><span>{n.label}</span></button>)}</nav><div className="q-sidebar-foot"><ShieldCheck size={14}/><span>لا تنفيذ من طبقة الواجهة</span></div></aside>
 <section className="q-main" style={{transform:`scale(${1+(scale-100)/1000})`,transformOrigin:'top center'}}><div className="q-heading glass"><div><span className="eyebrow"><Icon size={13}/> AMAR AI / {view.toUpperCase()}</span><h1>{view==='home'?'مساحة الذكاء الآمنة':active.label}</h1><p>واجهة متحركة ومتجاوبة؛ Item 10 يحتفظ بالقرار، التحقق، الأدلة، الذاكرة والحوكمة.</p></div>{panels.core&&<div className="core-orb"><div className="core-ring ring-1"/><div className="core-ring ring-2"/><div className="core-ring ring-3"/><span>Q</span><small>{m.label}</small></div>}<Eye onClick={()=>toggle('core')} size={16}/></div>
 <section className="search-mode glass"><div><small>SEARCH POLICY</small><b>وضع البحث</b><span>اختيار الواجهة فقط؛ لا يتجاوز الصلاحيات أو الموافقات.</span></div><div className="mode-switch"><button className={searchMode==='restricted'?'selected':''} onClick={()=>setSearchMode('restricted')} disabled={cap.searchRestricted===false}><LockKeyhole size={15}/> بحث بقيود</button><button className={searchMode==='open'?'selected':''} onClick={()=>setSearchMode('open')} disabled={cap.searchOpen!==true}><Globe2 size={15}/> بحث مفتوح</button></div></section>
 {view==='home'&&<Home onNav={setView} cap={cap}/>} {view==='assistant'&&<Assistant r={response} copy={copy}/>} {view==='research'&&<Research sources={sources} run={research} enabled={Boolean(bridge?.search)} evidence={evidence} setEvidence={setEvidence} available={hasEvidence}/>} {view==='workspace'&&<Workspace notes={notes} active={activeNote} draft={draft} setDraft={setDraft} create={create} open={open} save={save} del={del} copy={copy}/>} {view==='files'&&<Files pick={()=>fileRef.current?.click()} image={()=>imageRef.current?.click()} video={()=>videoRef.current?.click()} cap={cap}/>} {view==='memory'&&<Memory/>}{view==='analytics'&&<Analytics/>}{view==='settings'&&<Settings theme={theme} setTheme={setTheme} color={color} setColor={setColor} size={size} setSize={setSize} weight={weight} setWeight={setWeight} palette={palette} setPalette={setPalette} scale={scale} setScale={setScale}/>} 
 {panels.progress&&<Progress index={stage} running={running}/>} {panels.sources&&<Sources sources={sources} response={response} evidence={evidence} setEvidence={setEvidence} available={hasEvidence}/>} 
 {panels.composer&&<section className="composer glass"><div className="composer-left"><button onClick={()=>fileRef.current?.click()}><Paperclip size={17}/></button><button onClick={()=>imageRef.current?.click()} disabled={cap.image!==true}><ImageIcon size={17}/></button><button onClick={()=>videoRef.current?.click()} disabled={cap.video!==true}><Video size={17}/></button><button disabled><Mic size={17}/></button><button onClick={()=>void share()} disabled={!bridge?.startScreenShare||cap.screenShare===false} className={sharing?'screen-live':''}>{sharing?<Square size={15}/>:<MonitorUp size={17}/>}</button></div><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void submit()}}} placeholder="اكتب طلبًا… لا تظهر النتيجة قبل حالة تحقق صحيحة من Item 10" rows={2}/><button className="send" onClick={()=>void submit()} disabled={!bridge?.send||running}><Send size={16}/></button><Eye onClick={()=>toggle('composer')} size={16}/></section>}
 {sharing&&<div className="screen-share-banner glass"><span className="live-dot"/><b>الشاشة قيد المشاركة</b><span>لا تحكم حساس دون تأكيد المستخدم.</span><button onClick={()=>void share()}><Square size={13}/> Stop</button></div>}
 {panels.activity&&<section className="activity-panel glass"><div className="panel-title"><b>SESSION SAFETY</b></div><div className="activity-row"><span><Activity size={14}/> {m.label}</span><span><LockKeyhole size={14}/> الصلاحيات خارج UI</span><span><ShieldCheck size={14}/> Fail-Closed</span><span><Zap size={14}/> Item 10 adapter</span></div></section>}
 {panels.editor&&<Editor style={style} palette={palette} setPalette={setPalette} copy={()=>void copy(draft)} paste={()=>void paste()} />}
 <footer className="q-footer"><span>AMAR AI · ITEM 10 UI</span><span>القرار والتحقق خارج طبقة الواجهة</span><span>{sharing?'SCREEN SHARE ACTIVE':'READY'} · FAIL-CLOSED</span></footer></section></div>
 <input ref={fileRef} hidden type="file" multiple onChange={e=>{const f=e.target.files?.[0];if(f)void analyze(f);e.currentTarget.value=''}}/><input ref={imageRef} hidden type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)void analyze(f);e.currentTarget.value=''}}/><input ref={videoRef} hidden type="file" accept="video/*" onChange={e=>{const f=e.target.files?.[0];if(f)void analyze(f);e.currentTarget.value=''}}/></main>;
}
function Home({onNav,cap}:{onNav:(v:ViewId)=>void;cap:Capabilities}){const cards:[ViewId,typeof Bot,string,string][]=[['assistant',Bot,'AI Assistant','نص وحالات تحقق، وأدلة عند توفرها.'],['research',Globe2,'Research','بحث بقيود أو مفتوح وفق صلاحيات Item 10.'],['workspace',FolderOpen,'Workspace','مفكرة وصفحات متعددة.'],['files',FileSearch,'File Analysis','ملفات وصور وفيديو دون تنفيذ تلقائي.'],['memory',BrainCircuit,'Memory','عرض فقط.'],['analytics',BarChart3,'Analytics','مؤشرات عند وصول بيانات موثوقة.']];return <div className="home-grid">{cards.map(([id,I,t,x])=><button className="module-card glass" key={id} onClick={()=>onNav(id)}><div className="module-icon"><I size={19}/></div><div><small>AMAR MODULE</small><b>{t}</b><p>{x}</p>{id==='research'&&<small>{cap.searchOpen===true?'Open search available':'Open search unavailable'}</small>}</div><ChevronLeft size={16}/></button>)}</div>}
function Assistant({r,copy}:{r:AmarAgentResponse|null;copy:(s:string)=>void}){return <div className="assistant-view"><div className="chat-state glass"><div className="chat-avatar"><Bot size={25}/></div><div><small>ITEM 10</small><b>النتيجة لا تظهر إلا بعد التحقق</b><p>المراحل آمنة فقط؛ لا Chain-of-Thought.</p></div><div className="voice-tools"><button disabled><Volume2 size={17}/></button><button disabled><Mic size={17}/></button></div></div>{r?<article className={`message-card glass verification-${r.verification||'uncertain'}`}><span className="message-tag">{r.verification==='confirmed'?'Confirmed':r.verification==='blocked'?'Blocked':'Uncertain'}</span>{r.verification==='confirmed'&&r.status==='complete'?<><p>{r.text}</p>{r.durationMs!=null&&<small>الزمن: {r.durationMs} ms</small>}<button onClick={()=>copy(r.text)}><Clipboard size={14}/> نسخ</button></>:<div className="uncertainty-box"><CircleAlert size={18}/><div><b>{r.verification==='blocked'?'العملية محجوبة':'الأدلة غير كافية للتأكيد'}</b><p>{r.uncertaintyReason||r.text}</p></div></div>}</article>:<div className="empty-state glass"><MessageSquare size={26}/><b>لا توجد نتيجة</b><span>ابدأ بعد ربط عقد Item 10.</span></div>}</div>}
function Research({sources,run,enabled,evidence,setEvidence,available}:{sources:AmarSource[];run:()=>void;enabled:boolean;evidence:boolean;setEvidence:(v:boolean)=>void;available:boolean}){return <div className="research-view"><div className="research-bar glass"><Search size={17}/><span>استعلام البحث من مربع الإدخال السفلي</span><button onClick={run} disabled={!enabled}><Play size={14}/> ابدأ البحث</button></div><div className="research-layout"><div className="research-main glass"><div className="panel-title"><b>COMPARISON MATRIX</b><span>الأدلة والتعارضات من Item 10 فقط</span></div>{sources.length?<div className="matrix">{sources.map((s,i)=><div key={s.id}><span>{i+1}</span><b>{s.title}</b><em>{s.confidence??'—'}%</em><small>{s.status==='conflict'?'تعارض':s.status==='verified'?'موثق':'قيد التحقق'}</small></div>)}</div>:<div className="empty-state"><Globe2 size={24}/><b>لا توجد أدلة مستلمة</b><span>لن تُنشئ الواجهة مصادر من تلقاء نفسها.</span></div>}</div><div className="confidence glass"><Gauge size={20}/><small>CONFIDENCE</small><strong>{sources.length?`${Math.round(sources.reduce((a,s)=>a+(s.confidence??0),0)/sources.length)}%`:'—'}</strong></div></div>{available&&<button className="evidence-button" onClick={()=>setEvidence(!evidence)}>{evidence?'إخفاء الأدلة والمصادر':'عرض الأدلة والمصادر'}</button>}</div>}
function Workspace({notes,active,draft,setDraft,create,open,save,del,copy}:{notes:Note[];active:string|null;draft:string;setDraft:(s:string)=>void;create:()=>void;open:(n:Note)=>void;save:()=>void;del:()=>void;copy:(s:string)=>void}){return <div className="workspace-view"><div className="workspace-tree glass"><div className="panel-title"><b>NOTEBOOK</b><button onClick={create}><Plus size={14}/></button></div>{notes.map(n=><button className={active===n.id?'tree-row active':'tree-row'} key={n.id} onClick={()=>open(n)}><FileText size={15}/><span>{n.title}</span></button>)}</div><div className="workspace-canvas glass"><div className="canvas-head"><span>EDITOR</span><div><button onClick={()=>copy(draft)} disabled={!active}><Clipboard size={14}/></button><button onClick={save} disabled={!active}><Save size={14}/></button><button onClick={del} disabled={!active}><Trash2 size={14}/></button></div></div><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="اكتب هنا…" disabled={!active}/></div></div>}
function Files({pick,image,video,cap}:{pick:()=>void;image:()=>void;video:()=>void;cap:Capabilities}){const xs:[typeof FileText,string,()=>void,boolean][]=[[FileText,'PDF / TXT / DOC',pick,cap.text===true],[FileArchive,'ZIP / ARCHIVE',pick,cap.text===true],[FileCode2,'CODE / JSON / LOG',pick,cap.text===true],[FileImage,'IMAGE',image,cap.image===true],[Video,'VIDEO',video,cap.video===true],[Link2,'EXTERNAL LINK',()=>{},false]];return <div className="files-view"><div className="file-action-grid">{xs.map(([I,t,a,on])=><button key={t} className="drop-zone glass" onClick={a} disabled={!on}><I size={22}/><b>{t}</b><span>{on?'متاح عبر العقد المتصل':'غير متاحة بعد'}</span></button>)}</div><div className="pipeline glass"><div className="panel-title"><b>SAFE PRESENTATION PIPELINE</b><small>File → Scan → Parse → Analyze → Verify → Report</small></div><div className="pipeline-track">{['File','Scan','Parse','Analyze','Verify','Report'].map(x=><span key={x}><i/><b>{x}</b></span>)}</div></div></div>}
function Memory(){return <div className="memory-grid">{[['Saved info',Database],['Preferences',Settings2],['Past projects',FolderOpen],['Past results',History],['Sources',Globe2],['Retrieve',Search]].map(([t,I])=><div className="memory-card glass" key={t as string}><I size={19}/><b>{t as string}</b><p>العرض فقط؛ التنفيذ الفعلي خارج UI.</p><button disabled>فتح <ChevronLeft size={13}/></button></div>)}</div>}
function Analytics(){return <div className="analytics-grid">{['Verification','Evidence','Errors','Performance'].map(t=><div className="analytics-card glass" key={t}><small>{t}</small><strong>—</strong><span>بانتظار بيانات موثوقة من Item 10</span></div>)}</div>}
function Settings(p:{theme:'aurora'|'obsidian';setTheme:(v:'aurora'|'obsidian')=>void;color:string;setColor:(v:string)=>void;size:number;setSize:(v:number)=>void;weight:number;setWeight:(v:number)=>void;palette:boolean;setPalette:(v:boolean)=>void;scale:number;setScale:(v:number)=>void}){return <div className="settings-view glass"><div className="setting"><div><b>Theme</b><small>واجهة ديناميكية</small></div><button onClick={()=>p.setTheme(p.theme==='aurora'?'obsidian':'aurora')}>{p.theme}</button></div><div className="setting"><div><b>لون الكتابة</b><small>محلي للمحرر</small></div><input type="color" value={p.color} onChange={e=>p.setColor(e.target.value)}/></div><div className="setting"><div><b>حجم الخط</b><small>12–32px</small></div><input type="range" min="12" max="32" value={p.size} onChange={e=>p.setSize(+e.target.value)}/></div><div className="setting"><div><b>سماكة الخط</b><small>300–800</small></div><input type="range" min="300" max="800" step="100" value={p.weight} onChange={e=>p.setWeight(+e.target.value)}/></div><div className="setting"><div><b>لوحة الألوان</b><small>إظهار / إخفاء</small></div><button onClick={()=>p.setPalette(!p.palette)}>{p.palette?'إخفاء':'إظهار'}</button></div><div className="setting"><div><b>حجم البطاقات</b><small>80–120%</small></div><input type="range" min="80" max="120" value={p.scale} onChange={e=>p.setScale(+e.target.value)}/></div><div className="setting"><ShieldCheck size={20}/><b>لا صلاحيات تنفيذية داخل UI</b></div></div>}
function Progress({index,running}:{index:number;running:boolean}){return <section className={`progress-panel glass ${running?'running':'collapsed-terminal'}`}><div className="panel-title"><b>SAFE OPERATIONAL PROGRESS</b><small>{running?'مراحل آمنة فقط':'تم تقليل شاشة التقدم'}</small></div><div className="progress-steps expanded-safe">{stages.map((s,i)=><div className={i<=index&&index>=0?'done':''} key={s.id}><span>{i<=index&&index>=0?<CheckCircle2 size={14}/>:i+1}</span><b>{s.label}</b>{i<stages.length-1&&<i/>}</div>)}</div><small className="progress-safety">لا يتم عرض التفكير الداخلي أو Chain-of-Thought.</small></section>}
function Sources({sources,response,evidence,setEvidence,available}:{sources:AmarSource[];response:AmarAgentResponse|null;evidence:boolean;setEvidence:(v:boolean)=>void;available:boolean}){return <section className="sources-panel glass"><div className="panel-title"><b>EVIDENCE & SOURCES</b><small>لا مصادر مصطنعة من الواجهة</small></div>{available?<><button className="evidence-button" onClick={()=>setEvidence(!evidence)}>{evidence?'إخفاء الأدلة والمصادر':'عرض الأدلة والمصادر'}</button>{evidence&&<div className="source-grid">{(response?.sources?.length?response.sources:sources).map(s=><div className="source-card" key={s.id}><div><b>{s.title}</b><p>{s.excerpt||'بدون مقتطف.'}</p><small>{s.status==='verified'?'موثق':s.status==='conflict'?'تعارض':'قيد التحقق'} {s.confidence!=null?`· ${s.confidence}%`:''}</small></div><MoreHorizontal size={15}/></div>)}</div>}</>:<div className="empty-state"><Globe2 size={22}/><span>الأدلة والمصادر غير متاحة بعد عبر العقد المتصل.</span></div>}</section>}
function Editor({style,palette,setPalette,copy,paste}:{style:CSSProperties;palette:boolean;setPalette:(v:boolean)=>void;copy:()=>void;paste:()=>void}){return <section className="editor-panel glass"><div className="panel-title"><b>EDITOR CONTROLS</b><small>إعدادات العرض المحلية</small></div><div className="editor-toolbar"><button onClick={copy}><Clipboard size={14}/> نسخ</button><button onClick={paste}><Download size={14}/> لصق</button><button onClick={()=>setPalette(!palette)}><Edit3 size={14}/> {palette?'إخفاء الألوان':'إظهار الألوان'}</button><span style={style}>Aa</span></div>{palette&&<div className="palette-row"><span>لون الكتابة</span><span className="palette-dot"/><span>حجم 12–32</span><span>سماكة 300–800</span></div>}</section>}
