package com.personal.gridbot.amaros.shell

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.core.*
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.personal.gridbot.amaros.core.AmarAppState
import com.personal.gridbot.amaros.core.AmarEvent
import com.personal.gridbot.amaros.core.AmarEventBus
import com.personal.gridbot.amaros.navigation.AmarRoom
import kotlin.math.cos
import kotlin.math.sin

private val BG=Color(0xFF02030A); private val ICE=Color(0xFFEFFFFF); private val CYAN=Color(0xFF32E9FF); private val VIOLET=Color(0xFFA86BFF); private val GREEN=Color(0xFF45F0A1); private val GOLD=Color(0xFFFFD166); private val PINK=Color(0xFFFF55C5); private val RED=Color(0xFFFF6575)

@Composable
fun AmarAuroraShell(initialState: AmarAppState=AmarAppState(),onOpenLegacyGrid:()->Unit={}){
 var entered by remember{mutableStateOf(false)}; var selected by remember{mutableIntStateOf(0)}; var spin by remember{mutableFloatStateOf(0f)}; var focus by remember{mutableIntStateOf(0)}; var state by remember{mutableStateOf(initialState)}
 val rooms=AmarRoom.entries; val tr=rememberInfiniteTransition(label="AMAR_NEXUS"); val t by tr.animateFloat(0f,1f,infiniteRepeatable(tween(9000),RepeatMode.Reverse),label="flow"); val p by tr.animateFloat(.72f,1f,infiniteRepeatable(tween(1300),RepeatMode.Reverse),label="pulse")
 Box(Modifier.fillMaxSize().background(BG)){Background(t,p);if(!entered)Portal(t,p){entered=true}else{World(rooms,selected,spin,t,p,focus,{spin+=it/160f},{i->{selected=i;focus=0;state=state.copy(selectedRoom=rooms[i]);AmarEventBus.publish(AmarEvent.RoomSelected(rooms[i].name))}},{focus=it},onOpenLegacyGrid)}}
}

@Composable private fun Background(t:Float,p:Float){Canvas(Modifier.fillMaxSize()){val w=size.width;val h=size.height;drawRect(Brush.radialGradient(listOf(CYAN.copy(.19f*p),Color.Transparent),Offset(w*(.18f+t*.16f),h*.15f),w*.72f));drawRect(Brush.radialGradient(listOf(VIOLET.copy(.16f),Color.Transparent),Offset(w*(.82f-t*.16f),h*.82f),w*.68f));drawRect(Brush.radialGradient(listOf(PINK.copy(.06f),Color.Transparent),Offset(w*.5f,h*.5f),w*.42f));for(i in 0..20){val y=h*i/20f;drawLine(Color.White.copy(.018f),Offset(0f,y),Offset(w,y),1f)}for(i in 0..16){val x=w*i/16f;drawLine(Color.White.copy(.012f),Offset(x,0f),Offset(x,h),1f)}}}

@Composable private fun Portal(t:Float,p:Float,enter:()->Unit){Box(Modifier.fillMaxSize().pointerInput(Unit){detectTapGestures{enter()}}){Canvas(Modifier.fillMaxSize()){val c=Offset(size.width/2,size.height/2);val r=size.minDimension*.23f;for(i in 0..7)drawCircle(CYAN.copy(.025f+i*.012f),r+i*34f,c,style=Stroke(1.2f));drawCircle(CYAN.copy(.3f),r,c,style=Stroke(3f));drawCircle(VIOLET.copy(.18f),r*.72f,c,style=Stroke(2f));for(i in 0..15){val a=t*6.28f+i*.4f;drawCircle(if(i%2==0)CYAN else VIOLET,3f+p*2f,Offset(c.x+cos(a)*r*1.27f,c.y+sin(a)*r*1.27f))}};Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Text("A M A R",color=ICE,fontSize=42.sp,fontWeight=FontWeight.Bold,letterSpacing=9.sp);Spacer(Modifier.height(5.dp));Text("AURORA NEXUS",color=CYAN,fontSize=13.sp,letterSpacing=4.sp);Spacer(Modifier.height(28.dp));Box(Modifier.clip(CircleShape).background(CYAN.copy(.13f)).padding(horizontal=32.dp,vertical=15.dp)){Text("دخول إلى النظام  ›",color=ICE,fontSize=16.sp,fontWeight=FontWeight.Bold)};Spacer(Modifier.height(12.dp));Text("DEMO • LOCAL • SAFE",color=Color.White.copy(.4f),fontSize=9.sp,letterSpacing=2.sp)}}}

@Composable private fun World(rooms:List<AmarRoom>,sel:Int,spin:Float,t:Float,p:Float,focus:Int,drag:(Float)->Unit,choose:(Int)->Unit,setFocus:(Int)->Unit,legacy:()->Unit){Column(Modifier.fillMaxSize().padding(12.dp)){Top(rooms[sel],p);Spacer(Modifier.height(10.dp));Box(Modifier.fillMaxSize()){Orbit(rooms,sel,spin,t,drag,choose,Modifier.align(Alignment.Start).width(118.dp).fillMaxHeight());AnimatedContent(rooms[sel],label="room",modifier=Modifier.fillMaxSize().padding(start=128.dp)){RoomCockpit(it,t,p,focus,setFocus,legacy)}}}}

@Composable private fun Top(r:AmarRoom,p:Float){Row(Modifier.fillMaxWidth().clip(RoundedCornerShape(28.dp)).background(Color.White.copy(.055f)).padding(14.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(9.dp*p).clip(CircleShape).background(GREEN));Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text("AMAR / NEXUS",color=ICE,fontSize=18.sp,fontWeight=FontWeight.Bold,letterSpacing=2.sp);Text("${r.emoji} ${r.titleAr} • XAUUSD • M5",color=Color.White.copy(.48f),fontSize=10.sp)}Text("DEMO",color=GOLD,fontSize=10.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.width(15.dp));Text("82% AI SCORE",color=CYAN,fontSize=10.sp,fontWeight=FontWeight.Bold)}}

@Composable private fun Orbit(rooms:List<AmarRoom>,sel:Int,spin:Float,t:Float,drag:(Float)->Unit,choose:(Int)->Unit,m:Modifier){Box(m.clip(RoundedCornerShape(32.dp)).background(Color.White.copy(.035f)).pointerInput(Unit){detectDragGestures{_,d->drag(d.y)}}){Canvas(Modifier.fillMaxSize()){val c=Offset(size.width/2,size.height/2);drawOval(CYAN.copy(.08f),center=c,radiusX=size.width*.32f,radiusY=size.height*.36f,style=Stroke(1.5f));drawOval(VIOLET.copy(.06f),center=c,radiusX=size.width*.24f,radiusY=size.height*.27f,style=Stroke(1f))};rooms.forEachIndexed{i,r->val a=(i-sel)*.72f+spin+t*.14f;val depth=(cos(a)+1f)/2f;val y=.5f+sin(a)*.39f;val active=i==sel;Box(Modifier.align(Alignment.TopCenter).offset(y=(y*1000f-500f).dp).graphicsLayer{val s=.72f+depth*.34f;scaleX=s+(if(active).1f else 0f);scaleY=scaleX;alpha=.35f+depth*.65f;rotationY=sin(a)*22f;cameraDistance=25f*density}.clip(RoundedCornerShape(20.dp)).background(if(active)CYAN.copy(.13f)else Color.Black.copy(.18f)).pointerInput(i){detectTapGestures{choose(i)}}.padding(9.dp)){Column(horizontalAlignment=Alignment.CenterHorizontally){Text(r.emoji,fontSize=if(active)24.sp else 18.sp);Text(r.titleAr.take(8),color=if(active)ICE else Color.White.copy(.45f),fontSize=8.sp,fontWeight=if(active)FontWeight.Bold else FontWeight.Normal)}}}}}

@Composable private fun RoomCockpit(r:AmarRoom,t:Float,p:Float,f:Int,s:(Int)->Unit,legacy:()->Unit){Column(Modifier.fillMaxSize()){Text(r.titleAr,color=ICE,fontSize=28.sp,fontWeight=FontWeight.Bold);Text("${r.name.replace('_',' ')} • LIVING COCKPIT",color=CYAN,fontSize=9.sp,letterSpacing=2.sp);Spacer(Modifier.height(12.dp));when(r){AmarRoom.COMMAND_CENTER->CoreRoom(t,p,f,s);AmarRoom.MARKET->MarketRoom(t,f,s);AmarRoom.CHART->ChartRoom(t,f,s);AmarRoom.BOT_LAB->BotRoom(t,p,f,s,legacy);AmarRoom.RISK->RiskRoom(t,p,f,s);else->GenericRoom(r,f,s)}}}

@Composable private fun CoreRoom(t:Float,p:Float,f:Int,s:(Int)->Unit){Row(Modifier.fillMaxSize(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Core("AMAR CORE","MONITORING",CYAN,t,p,Modifier.weight(1.3f));Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(9.dp)){Panel("MARKET","BUY • 82%",CYAN,f==0){s(0)};Panel("BOT","ACTIVE / DEMO",GREEN,f==1){s(1)};Panel("RISK","SAFE / 5%",GOLD,f==2){s(2)};Panel("EQUITY","$1,012.84",VIOLET,f==3){s(3)}}}}
@Composable private fun MarketRoom(t:Float,f:Int,s:(Int)->Unit){Row(Modifier.fillMaxSize(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Chart(t,CYAN,Modifier.weight(1.5f));Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(9.dp)){Panel("DIRECTION","BUY",CYAN,f==0){s(0)};Panel("STRENGTH","82%",GREEN,f==1){s(1)};Panel("VOLATILITY","HIGH",PINK,f==2){s(2)};Panel("SESSION","LONDON",GOLD,f==3){s(3)}}}}
@Composable private fun ChartRoom(t:Float,f:Int,s:(Int)->Unit){Column(Modifier.fillMaxSize(),verticalArrangement=Arrangement.spacedBy(9.dp)){Chart(t,CYAN,Modifier.weight(1f));Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(7.dp)){listOf("EMA","VWAP","FVG","BOS","TP","SL").forEachIndexed{i,x->Panel(x,if(i%2==0)"ON" else "LIVE",if(i%3==0)CYAN else VIOLET,f==i,Modifier.width(100.dp)){s(i)}}}}}
@Composable private fun BotRoom(t:Float,p:Float,f:Int,s:(Int)->Unit,legacy:()->Unit){Row(Modifier.fillMaxSize(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Core("AMAR GRID","ANALYZING",GOLD,t,p,Modifier.weight(1.15f));Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(7.dp)){Dial("LOT","0.02",GOLD,f==0){s(0)};Dial("GRID STEP","40",CYAN,f==1){s(1)};Dial("MAX ORDERS","30",VIOLET,f==2){s(2)};Dial("MULTIPLIER","2.00",PINK,f==3){s(3)};Panel("EXISTING GRID ENGINE","OPEN",GOLD,f==4){s(4);legacy()}}}}
@Composable private fun RiskRoom(t:Float,p:Float,f:Int,s:(Int)->Unit){Row(Modifier.fillMaxSize(),horizontalArrangement=Arrangement.spacedBy(12.dp)){Core("RISK RADAR","PROTECTED",GREEN,t,p,Modifier.weight(1.1f));Column(Modifier.weight(1f),verticalArrangement=Arrangement.spacedBy(7.dp)){Dial("RISK","5%",GREEN,f==0){s(0)};Dial("DAILY LOSS","10%",GOLD,f==1){s(1)};Dial("MAX LOT","0.20",CYAN,f==2){s(2)};Dial("BASKET SL","$100",RED,f==3){s(3)}}}}

@Composable private fun GenericRoom(r:AmarRoom,f:Int,s:(Int)->Unit){val v=when(r){AmarRoom.POSITIONS->listOf("6 OPEN","18 PENDING","+12.84 FLOAT","0.12 SPREAD");AmarRoom.PERFORMANCE->listOf("+18.40 TODAY","+127.40 TOTAL","66.7% WIN","2.1% DD");AmarRoom.INDICATORS->listOf("EMA TREND","RSI 64","VWAP ABOVE","ATR HIGH");AmarRoom.ANALYSIS->listOf("BUY BIAS","82 SCORE","MOMENTUM","M5 REGIME");AmarRoom.TESTING->listOf("BACKTEST","FORWARD","MONTE CARLO","PARAMETERS");AmarRoom.TOOLS->listOf("RISK SIZE","LOT SIZE","TP / SL","GRID CALC");AmarRoom.ALERTS->listOf("CONNECTION","RISK ARMED","TP / SL","REBUILD");AmarRoom.LIBRARY->listOf("CORE","INDICATORS","STRATEGIES","EXTENSIONS");else->listOf("MOTION HIGH","AURORA","DEMO SAFE","SECURITY")};val a=when(r){AmarRoom.ALERTS->PINK;AmarRoom.RISK->GREEN;AmarRoom.PERFORMANCE->GOLD;else->VIOLET};Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().horizontalScroll(rememberScrollState()),horizontalArrangement=Arrangement.spacedBy(9.dp)){v.forEachIndexed{i,x->Panel("NODE ${i+1}",x,a,f==i,Modifier.width(175.dp)){s(i)}}};Spacer(Modifier.height(12.dp));Core("${r.name} SPACE","LIVE DATA",a,0f,1f,Modifier.fillMaxSize())}}

@Composable private fun Core(title:String,status:String,a:Color,t:Float,p:Float,m:Modifier){Box(m.clip(RoundedCornerShape(30.dp)).background(Color.White.copy(.045f))){Canvas(Modifier.fillMaxSize()){val c=Offset(size.width/2,size.height/2+sin(t*6.28f)*10f);for(i in 0..6)drawCircle(a.copy(.025f+i*.014f),size.minDimension*(.15f+i*.05f),c,style=Stroke(1.2f));drawCircle(a.copy(.3f),size.minDimension*.17f*p,c,style=Stroke(3f));for(i in 0..8){val q=t*6.28f+i*.7f;drawCircle(a.copy(.75f),3f+p,Offset(c.x+cos(q)*size.minDimension*.22f,c.y+sin(q)*size.minDimension*.22f))}};Column(Modifier.align(Alignment.Center),horizontalAlignment=Alignment.CenterHorizontally){Text("◈",color=a,fontSize=48.sp);Text(title,color=ICE,fontSize=20.sp,fontWeight=FontWeight.Bold,letterSpacing=2.sp);Text(status,color=a,fontSize=9.sp,letterSpacing=3.sp);Spacer(Modifier.height(14.dp));Text("LIVE • REACTIVE",color=GREEN,fontSize=9.sp)}}}

@Composable private fun Chart(t:Float,a:Color,m:Modifier){Box(m.clip(RoundedCornerShape(28.dp)).background(Color.White.copy(.04f))){Canvas(Modifier.fillMaxSize().padding(14.dp)){for(i in 0..10){val y=size.height*i/10f;drawLine(Color.White.copy(.035f),Offset(0f,y),Offset(size.width,y),1f)};val path=Path();for(i in 0..90){val x=size.width*i/90f;val y=size.height*.58f-sin(i*.27f+t*5f)*size.height*.11f-i*size.height*.0023f;if(i==0)path.moveTo(x,y)else path.lineTo(x,y)};drawPath(path,a,style=Stroke(3f));drawCircle(GREEN,5f,Offset(size.width*.82f,size.height*.34f))};Text("XAUUSD • M5 • LIVING FLOW",Modifier.align(Alignment.TopStart).padding(14.dp),color=Color.White.copy(.5f),fontSize=9.sp)}}

@Composable private fun Panel(label:String,value:String,a:Color,active:Boolean,m:Modifier=Modifier.weight(1f),click:()->Unit){Box(m.clip(RoundedCornerShape(20.dp)).background(if(active)a.copy(.13f)else Color.White.copy(.045f)).pointerInput(label){detectTapGestures{click()}}.padding(12.dp)){Column{Text(label,color=Color.White.copy(.38f),fontSize=8.sp,letterSpacing=1.sp);Spacer(Modifier.height(4.dp));Text(value,color=if(active)ICE else a,fontSize=13.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(5.dp));Box(Modifier.fillMaxWidth().height(2.dp).clip(CircleShape).background(a.copy(if(active).9f else .3f)))}}}

@Composable private fun Dial(label:String,value:String,a:Color,active:Boolean,click:()->Unit){Row(Modifier.fillMaxWidth().clip(RoundedCornerShape(19.dp)).background(if(active)a.copy(.13f)else Color.White.copy(.045f)).pointerInput(label){detectTapGestures{click()}}.padding(11.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(40.dp).clip(CircleShape).background(a.copy(.1f))){Canvas(Modifier.fillMaxSize()){drawArc(a,-90f,270f,false,style=Stroke(3f));drawCircle(a.copy(.7f),3.5f,Offset(size.width/2,6f))}};Spacer(Modifier.width(9.dp));Column(Modifier.weight(1f)){Text(label,color=Color.White.copy(.4f),fontSize=8.sp,letterSpacing=1.sp);Text(value,color=ICE,fontSize=14.sp,fontWeight=FontWeight.Bold)};Text("DRAG",color=a.copy(.7f),fontSize=8.sp)}}
