export type AmarDecision = {
  direction: 'BUY' | 'SELL' | 'NEUTRAL';
  confidence: number;
  rationale: string[];
  riskState: 'SAFE' | 'WARNING' | 'EMERGENCY';
};

export type AmarIntelligenceSnapshot = {
  memoryReady: boolean;
  knowledgeReady: boolean;
  analyticsReady: boolean;
  decisionReady: boolean;
  confidence: number;
  explainability: string[];
  ethicsGate: 'PASS' | 'BLOCK';
};

/**
 * Explicitly non-trading demo state.
 * Never present fabricated confidence, direction, or readiness as live intelligence.
 */
export const DEMO_INTELLIGENCE: AmarIntelligenceSnapshot = {
  memoryReady: false,
  knowledgeReady: false,
  analyticsReady: false,
  decisionReady: false,
  confidence: 0,
  explainability: [
    'Demo state only — no verified market evidence is attached.',
    'No trading direction is generated by this fallback module.',
    'Live decisions require the AMAR intelligence and validation pipeline.'
  ],
  ethicsGate: 'BLOCK',
};

export function demoDecision(): AmarDecision {
  return {
    direction: 'NEUTRAL',
    confidence: 0,
    rationale: DEMO_INTELLIGENCE.explainability,
    riskState: 'WARNING',
  };
}
