package com.personal.gridbot.amaros.bots

import androidx.compose.animation.animateColorAsState
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.personal.gridbot.amaros.runtime.AmarBotCommandEngine
import com.personal.gridbot.amaros.runtime.AmarBotOperationalEngine
import kotlinx.coroutines.launch

private val V1Bg=Color(0xFF050C14);private val V1Panel=Color(0xFF0A1722);private val V1Cell=Color(0xFF0E2230);private val V1Line=Color(0xFF1A3E4D);private val V1Text=Color(0xFFE9FBFF);private val V1Muted=Color(0xFF7896A5);private val V1Cyan=Color(0xFF1DE5FF);private val V1Gold=Color(0xFFFFC84A);private val V1Green=Color(0xFF00E6A0);private val V1Red=Color(0xFFFF4F67);private val V1Yellow=Color(0xFFFFC84A)

enum class AmarBotCommandVisualState { CLOSED, WAITING, ACTIVE }

@Composable
fun AmarBotLabInterface1Screen(onBackHome:()->Unit){
 val context=androidx.compose.ui.platform.LocalContext.current;val repo=remember(context){AmarBotVaultRepository(context)};val command=remember(context){AmarBotCommandEngine(context)};val operational=remember(context){AmarBotOperationalEngine(context)};val scope=rememberCoroutineScope();var bots by remember{mutableStateOf(repo.load())};var selectedBot by remember{mutableIntStateOf(AmarBotLabSelectionContext.selectedBot.coerceIn(1,10))};var selectedStrategy by remember{mutableIntStateOf(1)};var notice by remember{mutableStateOf("")};var commandStates by remember{mutableStateOf(mapOf<String,AmarBotCommandVisualState>())};val bot=bots.firstOrNull{it.botNumber==selectedBot}?:bots.firstOrNull();val strategy=bot?.strategies?.firstOrNull{it.number==selectedStrategy}
 LaunchedEffect(Unit){runCatching{operational.ensureBotCatalog()}}
 fun issue(label:String,state:AmarBotCommandVisualState){commandStates=commandStates+(label to AmarBotCommandVisualState.WAITING);scope.launch{runCatching{command.queue(selectedBot,label)}.onSuccess{commandStates=commandStates+(label to state);notice="✓ الطلب #$it محفوظ"}.onFailure{commandStates=commandStates+(label to AmarBotCommandVisualState.CLOSED);notice="✕ ${it.message?:"تعذر حفظ الطلب"}"}}}
 Surface(Modifier.fillMaxSize(),color=V1Bg){Column(Modifier.fillMaxSize()){Row(Modifier.fillMaxWidth().background(V1Panel).padding(horizontal=10.dp,vertical=8.dp),verticalAlignment=Alignment.CenterVertically){Button(onClick=onBackHome,colors=ButtonDefaults.buttonColors(containerColor=V1Gold,contentColor=Color.Black),contentPadding=PaddingValues(horizontal=12.dp,vertical=3.dp)){Text("⌂",fontWeight=FontWeight.Black)};Spacer(Modifier.width(8.dp));Column(Modifier.weight(1f)){Text("AMAR BOT LAB",color=V1Cyan,fontSize=18.sp,fontWeight=FontWeight.Black);Text("البوت V$selectedBot • الاستراتيجية V$selectedStrategy",color=V1Muted,fontSize=9.sp)};Text("جاهز",color=V1Green,fontSize=9.sp,fontWeight=FontWeight.Black)}
 LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(8.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){item{CompactSelector("البوتات",selectedBot){selectedBot=it;AmarBotLabSelectionContext.selectedBot=it;selectedStrategy=1}};item{CompactSelector("الاستراتيجيات",selectedStrategy){selectedStrategy=it}};item{AmarSharedMarketStatus()};item{StrategyEditor1(strategy,selectedStrategy,{value->repo.saveStrategy(selectedBot,value);bots=repo.load();notice="✓ تم حفظ الاستراتيجية V${value.number}"},{repo.deleteStrategy(selectedBot,selectedStrategy);bots=repo.load();notice="تم حذف الاستراتيجية V$selectedStrategy"})};item{Card(colors=CardDefaults.cardColors(V1Panel),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){Text("أوامر البوت",color=V1Text,fontSize=13.sp,fontWeight=FontWeight.Black);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){listOf("تشغيل" to AmarBotCommandVisualState.ACTIVE,"إطفاء" to AmarBotCommandVisualState.CLOSED,"إغلاق الكل" to AmarBotCommandVisualState.CLOSED,"إعادة البناء" to AmarBotCommandVisualState.ACTIVE).forEach{(label,target)->CommandStateButton(label,commandStates[label]?:AmarBotCommandVisualState.CLOSED,target){issue(label,target)}}}}};if(notice.isNotBlank())item{Text(notice,color=V1Cyan,fontSize=9.sp,modifier=Modifier.fillMaxWidth().background(V1Cell,RoundedCornerShape(12.dp)).padding(10.dp))}}}}
}

@Composable private fun CompactSelector(title:String,selected:Int,onSelect:(Int)->Unit){Card(colors=CardDefaults.cardColors(V1Panel),shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(8.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween,verticalAlignment=Alignment.CenterVertically){Text(title,color=V1Text,fontSize=12.sp,fontWeight=FontWeight.Black);Text("V1–V10",color=V1Muted,fontSize=8.sp)};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(3.dp)){(1..10).forEach{n->val c by animateColorAsState(if(n==selected)V1Cyan else V1Cell,label="v1-$title-$n");Box(Modifier.weight(1f).height(31.dp).background(c,RoundedCornerShape(7.dp)).border(1.dp,if(n==selected)V1Cyan else V1Line,RoundedCornerShape(7.dp)).clickable{onSelect(n)},contentAlignment=Alignment.Center){Text("V$n",color=if(n==selected)Color.Black else V1Text,fontSize=8.sp,fontWeight=FontWeight.Black)}}}}}}

@Composable private fun CommandStateButton(label:String,state:AmarBotCommandVisualState,target:AmarBotCommandVisualState,onClick:()->Unit){val color=when(state){AmarBotCommandVisualState.ACTIVE->V1Green;AmarBotCommandVisualState.WAITING->V1Yellow;AmarBotCommandVisualState.CLOSED->V1Red};Button(onClick=onClick,modifier=Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=color,contentColor=if(state==AmarBotCommandVisualState.WAITING)Color.Black else Color.Black)){Text(if(state==AmarBotCommandVisualState.WAITING)"$label • جارٍ" else label,fontSize=7.sp,fontWeight=FontWeight.Black)}}

@Composable private fun StrategyEditor1(strategy:AmarSavedStrategy?,number:Int,onSave:(AmarSavedStrategy)->Unit,onDelete:()->Unit){var name by remember(strategy?.number,strategy?.name){mutableStateOf(strategy?.name?:"استراتيجية V$number")};var lot by remember(strategy?.number,strategy?.profile?.lot){mutableDoubleStateOf(strategy?.profile?.lot?:0.01)};var grid by remember(strategy?.number,strategy?.profile?.gridStep){mutableDoubleStateOf(strategy?.profile?.gridStep?:30.0)};var maxOrders by remember(strategy?.number,strategy?.profile?.maxOrders){mutableDoubleStateOf((strategy?.profile?.maxOrders?:10).toDouble())};var multiplier by remember(strategy?.number,strategy?.profile?.multiplier){mutableDoubleStateOf(strategy?.profile?.multiplier?:2.0)};var tp by remember(strategy?.number,strategy?.profile?.basketTp){mutableDoubleStateOf(strategy?.profile?.basketTp?:50.0)};var sl by remember(strategy?.number,strategy?.profile?.basketSl){mutableDoubleStateOf(strategy?.profile?.basketSl?:-30.0)};var trailing by remember(strategy?.number,strategy?.profile?.trailing){mutableDoubleStateOf(strategy?.profile?.trailing?:0.0)};var buy by remember(strategy?.number,strategy?.profile?.buyEnabled){mutableStateOf(strategy?.profile?.buyEnabled?:true)};var sell by remember(strategy?.number,strategy?.profile?.sellEnabled){mutableStateOf(strategy?.profile?.sellEnabled?:true)}
 Card(colors=CardDefaults.cardColors(V1Panel),shape=RoundedCornerShape(18.dp)){Column(Modifier.padding(10.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Text("إعدادات V$number",color=V1Gold,fontSize=15.sp,fontWeight=FontWeight.Black);OutlinedTextField(name,{name=it},Modifier.fillMaxWidth(),label={Text("اسم الاستراتيجية")},singleLine=true);AmarDragValueControl("اللوت",lot,.01,1.0,.01,V1Cyan,"%.2f",{lot=it},Modifier.fillMaxWidth());AmarDragValueControl("المسافة",grid,1.0,300.0,1.0,V1Cyan,"%.0f",{grid=it},Modifier.fillMaxWidth());AmarDragValueControl("أقصى الأوامر",maxOrders,1.0,100.0,1.0,V1Gold,"%.0f",{maxOrders=it},Modifier.fillMaxWidth());AmarDragValueControl("مضاعف اللوت",multiplier,1.0,5.0,.01,V1Gold,"%.2f",{multiplier=it},Modifier.fillMaxWidth());AmarDragValueControl("هدف السلة $",tp,0.0,500.0,.5,V1Green,"%.1f",{tp=it},Modifier.fillMaxWidth());AmarDragValueControl("وقف السلة $",sl,-500.0,0.0,.5,V1Red,"%.1f",{sl=it},Modifier.fillMaxWidth());AmarDragValueControl("التريلينج $",trailing,0.0,300.0,.5,V1Cyan,"%.1f",{trailing=it},Modifier.fillMaxWidth());Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){Button({buy=!buy},Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=if(buy)V1Green else V1Cell,contentColor=Color.Black)){Text(if(buy)"شراء ON" else "شراء OFF",fontSize=9.sp)};Button({sell=!sell},Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=if(sell)V1Green else V1Cell,contentColor=Color.Black)){Text(if(sell)"بيع ON" else "بيع OFF",fontSize=9.sp)}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(5.dp)){Button({onSave(AmarSavedStrategy(number,name.ifBlank{"استراتيجية V$number"},AmarBot1RuntimeConfig(lot,grid,maxOrders.toInt().coerceAtLeast(1),multiplier,tp,sl,trailing.coerceAtLeast(0.0),buy,sell)))},Modifier.weight(1f),colors=ButtonDefaults.buttonColors(containerColor=V1Green,contentColor=Color.Black)){Text("✓ حفظ",fontWeight=FontWeight.Black)};Button(onDelete,Modifier.weight(.45f),colors=ButtonDefaults.buttonColors(containerColor=V1Red)){Text("حذف")}}}}}
}

// CI revalidation marker: Interface 1 scope correction is intentionally isolated to this file.
